name: Lint And Test
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: psf/black@stable
          with:
            options: --check --verbose
        # Ruff Linter configuration set through pyproject.toml
        - uses: chartboost/ruff-action@v1

  test:
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12.0-alpha.7"]
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Run Tests
        run: |
          poetry run pytest
